apiVersion: apps/v1
kind: Deployment
metadata:
  name: tata-bank-prod
  namespace: dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tata-bank-prod
  template:
    metadata:
      labels:
        app: tata-bank-prod
    spec:
      containers:
        - name: tata-bank-prod
          image: 533267371412.dkr.ecr.us-east-2.amazonaws.com/tata-bank-prod:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: DB_URL
              valueFrom:
                secretKeyRef:
                  name: db-secrets-dev
                  key: DB_URL
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: db-secrets-dev
                  key: DB_USERNAME
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secrets-dev
                  key: DB_PASSWORD
            - name: JWT_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: db-secrets-dev
                  key: JWT_SECRET_KEY
            - name: JWT_EXPIRATION
              valueFrom:
                secretKeyRef:
                  name: db-secrets-dev
                  key: JWT_EXPIRATION

---
apiVersion: v1
kind: Service
metadata:
  name: tata-bank-prod-service
  namespace: dev
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:acm:us-east-1:533267371412:certificate/2de970ec-2b49-4668-bcf5-c7d8c0285ad2
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "443"
    service.beta.kubernetes.io/aws-load-balancer-connection-idle-timeout: "60"
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 80
      targetPort: 8080
      protocol: TCP
    - name: https
      port: 443
      targetPort: 8080
      protocol: TCP
  selector:
    app: tata-bank-prod
